FLAGS=-Wall -std=c++11  

all: variadic_args1 variadic_args2 

variadic_args1 : variadic_args1.cc
	$(CXX) variadic_args1.cc -o variadic_args1 $(FLAGS)
variadic_args2 : variadic_args2.cc
	$(CXX) variadic_args2.cc -o variadic_args2 $(FLAGS)
clean:
	rm -f variadic_args1 variadic_args2
